// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6zYsiTBZHo5nZ_vwcrkH5TuN5u_-pZJk',
    appId: '1:363031998930:web:0c816182c291f6ccba180b',
    messagingSenderId: '363031998930',
    projectId: 'desafio-cbec9',
    authDomain: 'desafio-cbec9.firebaseapp.com',
    storageBucket: 'desafio-cbec9.appspot.com',
    measurementId: 'G-WV0D759XKP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAm--HKXVtJi7_aMHx4eX8ldzwvVSP2IbA',
    appId: '1:363031998930:android:b4bba7292c3c082dba180b',
    messagingSenderId: '363031998930',
    projectId: 'desafio-cbec9',
    storageBucket: 'desafio-cbec9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClkonz3XAANdgg4TOTgOgeJx9AJ6jIspM',
    appId: '1:363031998930:ios:a52f360255deef1fba180b',
    messagingSenderId: '363031998930',
    projectId: 'desafio-cbec9',
    storageBucket: 'desafio-cbec9.appspot.com',
    iosClientId: '363031998930-qn5m3nlk8dlf7og94fg7rmcsv8kgtnp3.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafio',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClkonz3XAANdgg4TOTgOgeJx9AJ6jIspM',
    appId: '1:363031998930:ios:f1e56bdf9e6155ceba180b',
    messagingSenderId: '363031998930',
    projectId: 'desafio-cbec9',
    storageBucket: 'desafio-cbec9.appspot.com',
    iosClientId: '363031998930-itq5ubari629bri5ng26h9j5ttguv8gm.apps.googleusercontent.com',
    iosBundleId: 'com.example.desafio.RunnerTests',
  );
}
